export const Type = {
    GET_DATA: 'GET_DATA',
    GET_POST:'GET_POST',
    PUT_TITLE: 'PUT_TITLE',
    PUT_BODY:'PUT_BODY',
    PUT_COMMENT:'PUT_COMMENT',
    FLAG_POST:'FLAG_POST',
    FLAG_COMMENT:'FLAG_COMMENT',
    REDIRECT:'REDIRECT'
};